/** Onset bands carried in a beat map. */
export type OnsetBand = "kick" | "snare" | "hat";

/** Precomputed per-track timing data, generated by `yarn beatmap`. */
export interface BeatMap {
  id: string;
  version: number;
  /** Seconds. */
  duration: number;
  /** Constant tempo. */
  bpm: number;
  /** Seconds of beat index 0 (includes beat0Shift). */
  beat0: number;
  beatsPerBar: number;
  /** beatIndex ≡ downbeatMod (mod beatsPerBar) is a downbeat. */
  downbeatMod: number;
  /** 0..1; committed maps are 1. */
  confidence: number;
  curveFps: number;
  /** 0..255 loudness at curveFps. */
  energy: number[];
  /** 0..255 slow intensity at curveFps. */
  section: number[];
  /** Per bar index ≥ 0: 0 calm, 1 intense. */
  barLevels: number[];
  /** Flat [t0, s0, t1, s1, …]: t in seconds, s 0..1. */
  onsets: Record<OnsetBand, number[]>;
}

/** Everything visuals need for one animation frame. Mutated in place; read, never keep. */
export interface MusicFrame {
  /** Song seconds at the moment this frame is seen (latency-compensated). */
  time: number;
  isPlaying: boolean;
  bpm: number;
  /** Continuous beat position; negative before beat0. */
  beat: number;
  beatIndex: number;
  /** 0..1, 0 = on the beat. */
  beatPhase: number;
  barIndex: number;
  /** 0..1, 0 = downbeat. */
  barPhase: number;
  /** True only on the frame a beat boundary was crossed. */
  beatCrossed: boolean;
  /** beatCrossed && the crossed beat is a downbeat. */
  isDownbeat: boolean;
  timeToNextBeat: number;
  kick: number;
  snare: number;
  hat: number;
  energy: number;
  section: number;
  sectionLevel: 0 | 1;
  /** isDownbeat && sectionLevel differs from the previous bar's. */
  sectionChanged: boolean;
  /** 6 live bands, 0..1, texture only. */
  bands: Float32Array;
  beatConfidence: number;
}

export type EngineStatus = "idle" | "loading" | "ready" | "error";

/** Coarse engine state for React (via useSyncExternalStore). */
export interface EngineState {
  status: EngineStatus;
  unlocked: boolean;
  track: string | null;
  title: string | null;
  bpm: number | null;
  /** Playing or starting (a play is pending while the track decodes). */
  isPlaying: boolean;
  muted: boolean;
}

export interface TrackSource {
  id: string;
  title: string;
  url: string;
  loadBeatMap: () => Promise<BeatMap | null>;
}
